moduledir '/vagrant/deployment/puppet/module'
forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-concat', '1.2.4'
mod 'puppetlabs-stdlib', '4.9.0'
mod 'maestrodev/wget', '1.7.1'
mod 'jfryman/nginx', '0.2.7'
mod 'willdurand-nodejs', '1.8.5'
